/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalisthenicsRouteImport } from './routes/calisthenics'
import { Route as RunningRouteImport } from './routes/running'
import { Route as SummaryRouteImport } from './routes/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalisthenicsRoute = CalisthenicsRouteImport.update({
  id: '/calisthenics',
  path: '/calisthenics',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calisthenics': typeof CalisthenicsRoute
  '/running': typeof RunningRoute
  '/summary': typeof SummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calisthenics': typeof CalisthenicsRoute
  '/running': typeof RunningRoute
  '/summary': typeof SummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calisthenics': typeof CalisthenicsRoute
  '/running': typeof RunningRoute
  '/summary': typeof SummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/calisthenics' | '/running' | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/calisthenics' | '/running' | '/summary'
  id: '__root__' | '/' | '/auth' | '/calisthenics' | '/running' | '/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalisthenicsRoute: typeof CalisthenicsRoute
  RunningRoute: typeof RunningRoute
  SummaryRoute: typeof SummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calisthenics': {
      id: '/calisthenics'
      path: '/calisthenics'
      fullPath: '/calisthenics'
      preLoaderRoute: typeof CalisthenicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalisthenicsRoute: CalisthenicsRoute,
  RunningRoute: RunningRoute,
  SummaryRoute: SummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
